[server]
host = "localhost" # http host
port = 8082        # http port
timeout = 30       # http timeout
secure = false     # use https

[storage]
file = "db.sqlite" # database file
dir = "storage"    # files storage directory
timeout = 60       # db operation timeout (seconds)

[settings]
ttl = 604800           # max time to live (seconds) - 7 days
times = 100            # max times for users requests
size = 128             # max file size (Mb)
salt = "abc"           # additional key salt (replace it by a long random string for production)
gc = 10                # "garbage collector" timeout (seconds)
passlen = 15           # length for automatically created passwords
shutdown = 5           # shutdown server timeout (seconds)
templates = "html"     # folder with HTML templates
static = "html/static" # folder with static files, URL "/static/*"
